### DISCUSSION TITLE
Ampache Docker upgrade fails?

### DISCUSSION THREAD

**Discussion by gerroon** [ampache/ampache#4047] [Q&A] [answered]
Hi 

I just did a docker pull pull and facing an upgrade problem. Any recommendations?

```
This page handles all database updates to Ampache starting with 3.3.3.5. Your current version is 7.0.0 with database version 6.0.0 Build: 053

The following updates need to be performed:

Update failed. Please check the logs for further information.
```

docker compose

```
version: '3'

services:
  ampache:
    image: ampache/ampache:develop
    container_name: ampache
    restart: unless-stopped
    ports:
      - 10080:80
    volumes:
      - /media/ampache/config:/var/www/config
      - ./data/log:/var/log/ampache
      - /media:/media
      - /media/ampache/mysql_ampache:/var/lib/mysql


```
