### ISSUE TITLE
When use Add function on a remote catalog it re-adds the existing songs

### ISSUE THREAD

**Issue by manuelglez86** [ampache/ampache#1702]
# Environment

 * Ampache version: 3.8.6 (local), 3.8.4 (remote)
 * Web server + version: APACHE 2.4.7
 * Server operating system: UBUNTU 14
 * Client operating system:

 * Client type:
   - Web
   - Ampache
  

# Settings

# Description

I have 2 ampache instalation one local v3.8.6 and one remote 3.8.4.

I have added in 3.8.6 the remote catalog of 3.8.4, i have found that the Add function for remote catalogs have a bug that re-adds the songs to the local catalog (in my case 3.8.6) so if i have 4 songs in 3.8.4 when i use the add function (in local 3.8.6) then it will show 8 songs (in local 3.8.6), then again the add function now i have 12 songs and so on.

# Logs

**Comment by manuelglez86** [comment]
I trackeddown thru here 

[https://github.com/ampache/ampache/blob/4aa6f1332639009d66ba789d4068d611de450c5a/modules/catalog/remote/remote.catalog.php#L252](url)

The value of current is always Zero as you can see here:

[https://github.com/ampache/ampache/blob/4aa6f1332639009d66ba789d4068d611de450c5a/modules/catalog/remote/remote.catalog.php#L249](url)

so i think thats th problem, correct me if im wrong.

**Comment by manuelglez86** [comment]
its between

[here](https://github.com/ampache/ampache/blob/4aa6f1332639009d66ba789d4068d611de450c5a/modules/catalog/remote/remote.catalog.php#L266)

and

[here](https://github.com/ampache/ampache/blob/4aa6f1332639009d66ba789d4068d611de450c5a/modules/catalog/remote/remote.catalog.php#L334)

i think

**Comment by wagnered** [comment]
@manuelglez86 

Am able to duplicate, so I will take a look..

Thanks

**Comment by manuelglez86** [comment]
Hello again I made some debbugging and this is what i found

this function compares if the song already existe on the local using the URLs of the files:

```
public function check_remote_song($song)
    {
        $url = preg_replace('/ssid=.*&/', '', $song['url']);
        $sql        = 'SELECT `id` FROM `song` WHERE `file` = ?';
        $db_results = Dba::read($sql, array($url));
        if ($results = Dba::fetch_assoc($db_results)) {
            return $results['id'];
        }
        return false;
    }
```
So we have the url from remote:

> http://148.209.16.177:1039/386/play/index.php?ssid=680d75b0460ca93271ad4f6d0e863bfc&type=song&oid=10&uid=1&player=api&name=Desconocido%20-Hu-rfano-%20-%20RUADY.IU.042618.03.mp3

So this function is used to convert the remote url to local Url
``
$url = preg_replace('/ssid=.*&/', '', $song['url']);
``

And the result is a wrong URL (The funtion needs to elimnate only ths part ssid=680d75b0460ca93271ad4f6d0e863bfc&), but the actual result is:

> http://148.209.16.177:1039/386/play/index.php?name=Desconocido%20-Hu-rfano-%20-%20RUADY.IU.042618.03.mp3

So using this intead:
`$url = preg_replace('/ssid=\w*&/', '', $song['url']);`

will give a well formed url to compare:

`http://148.209.16.177:1039/386/play/index.php?type=song&oid=10&uid=1&player=api&name=Desconocido%20-Hu-rfano-%20-%20RUADY.IU.042618.03.mp3` 

And now the log show that the song already exist on local:

> 2018-04-24 09:22:34 [Soporte.Radio] (remote_catalog) -> Skipping existing song

If you think this is correct please let me know so I can make a pull request.

Thanks.

**Comment by wagnered** [comment]
Sorry to say that I ended up having to reboot my system and  after reboot, I could not reproduce your symptom.

I set both:
        `$url = preg_replace('/ssid=.*&/', '', $song['url']);`
        `$url1 = preg_replace('/ssid=\w*&/', '', $song['url']); `
in the check_remote_song function and got:
>http://localhost:8000/play/index.php?type=song&oid=14&uid=1&player=api&name=Alice%20Cooper%20-%2010%20Minutes%20Before%20the%20Worm.mp3

and I do not get additional adds when I perform a catalog add with the remote catalog.
The empty string ('') will replace/remove '/ssid=.*&/' or  '/ssid=\w*&/' all the way to the 't' in 'type' as long as there are no '&' in the middle of the string.

Also, I'm wondering where the string 'ssid=680d75b0460ca93271ad4f6d0e863bfc' came from. The  songs in my remote catalog do not contain any url strings starting with "ssid=".

**Comment by wagnered** [comment]
@manuelglez86 

Using the online page, I see it now.  If you want to do a PR make sure that you have the latest develop version and run php-cs-fixer before doing the push to your fork.

Otherwise, I can make the change and push to the develop branch.

I don't understand why this wasn't caught before. :smile: 

Thanks

**Comment by manuelglez86** [comment]
Im runing now 3.8.6 but let me configure an ampache-develop an I'll make the PR in a few days, regarding to me question Theres is a way to automatically update a remote catalog?

**Comment by wagnered** [comment]
By "remote catalog" I assume you mean the local catalog on the remote ampache installation?

On the remote system the file bin/catalog_update.inc could be set up with a cron job to routinely update the catalogs.

**Comment by manuelglez86** [comment]
>On the remote system the file bin/catalog_update.inc could be set up with a cron job to routinely update the catalogs.

but the changes are not reflected on the local system.

**Comment by wagnered** [comment]
Correct, and there is no way to automatically update the remote catalog on a local system, but you might copy/modify the local bin/catalog_update.inc to update the remote catalog.

**Comment by manuelglez86** [comment]
ok thank you i will take a look and try to modify the catalog_update.inc

**Comment by ftoledo** [comment]
i have this behavior using a dropbox remote catalog, i get same song twice:
i try to use the tool "find duplicates" but this get empty results. (maybe these tool are broken?)

how can i deal which this duplicates?

```
mysql> select * from song where id = 141451\G
*************************** 1. row ***************************
           id: 141451
         file: /Music/Elipsis/2018-05-01/01 - Pasado intermitente.mp3
      catalog: 31
        album: 13027
         year: 2018
       artist: 10606
        title: Pasado intermitente
      bitrate: 320000
         rate: 48000
         mode: cbr
         size: 11163996
         time: 1
        track: 1
         mbid: 
       played: 0
      enabled: 1
  update_time: 1525292436
addition_time: 1525289440
  user_upload: NULL
      license: NULL
     composer: 
     channels: 2
1 row in set (0.00 sec)

mysql> select * from song where id = 141452\G
*************************** 1. row ***************************
           id: 141452
         file: /Music/Elipsis/2018-05-01/01 - Pasado intermitente.mp3
      catalog: 31
        album: 13027
         year: 2018
       artist: 10606
        title: Pasado intermitente
      bitrate: 320000
         rate: 48000
         mode: cbr
         size: 11163996
         time: 1
        track: 1
         mbid: 
       played: 1
      enabled: 1
  update_time: 1525292441
addition_time: 1525289448
  user_upload: NULL
      license: NULL
     composer: 
     channels: 2
1 row in set (0.00 sec)

```
