### ISSUE TITLE
On web interface, cannot play any music. In chrome devtools I can see a log "AV is not defined".

### ISSUE THREAD

**Issue by Gateswong** [ampache/ampache#2514]
### Describe the bug

On web interface, I cannot play any music.

Opening the DevTools, the following exception is printed in the console:

```
Uncaught ReferenceError: AV is not defined
    at a.jPlayer._aurora_setAudio (jquery.jplayer.min.js:3)
    at String.<anonymous> (jquery.jplayer.min.js:3)
    at Function.each (jquery.min.js:2)
    at String.<anonymous> (jquery.jplayer.min.js:3)
    at Function.each (jquery.min.js:2)
    at a.jPlayer.setMedia (jquery.jplayer.min.js:3)
    at HTMLDivElement.<anonymous> (jquery.jplayer.min.js:2)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.a.fn.jPlayer (jquery.jplayer.min.js:2)
```

I can play music with no issue on my Android DSub app. Other clients not tested.

### Screenshots

Here is the bottom player panel, it seems like not fully loaded.

![image](https://user-images.githubusercontent.com/2586057/90827186-a23a9c80-e2f0-11ea-988e-897c92f23442.png)

## Environment

* Ampache version: 4.2.1
* Web server + version: Nginx 
* Server operating system: Linux (Docker)
* Client operating system: Windows (Chrome)

### Client type

* Web

**Comment by lachlan-00** [comment]
AV has something to do with the JS, i'll load a docker image and have a look

**Comment by lachlan-00** [comment]
i've tested with docker, it's possible the JS is being blocked in chrome? what version is it so i can test?

**Comment by AshotN** [comment]
Try in a different browser, Edge or Firefox. Also I haven't seen a coffee file in a long time, brings back memories.

**Comment by lachlan-00** [comment]
I kind of recreated this using a localhost web server. You're using docker but how are you accessing this?

I couldn't recreate this in docker.

**Comment by Gateswong** [comment]
Here is my docker-compose.yml:

```
version: '3'

services:
    ampache:
        image: ampache/ampache
        ports:
            - 5001:80
        environment:
            - CRON_JOB_UPDATE_CATALOGS=0 4 * * *
            - TZ=America/Los Angelas
            - MEMORY_CACHE_ENABLED=true
            - MEMORY_LIMIT=1024
        volumes: 
            - cifsshare_ampache_music:/media/Music
            - cifsshare_ampache_video:/media/Video
            - cifsshare_ampache_podcast:/media/Podcast
            - ./ampache-config:/var/www/html/config
            - ./ampache-themes:/var/www/html/themes
        restart: unless-stopped
```

I tried with both direct access https://domain.to.this.machine:5001/ (this is accessing within LAN) and https://domain.to.nginx.machine (this domain has public IP) which do a proxy_pass to this app.

Both have this issues.
