### ISSUE TITLE
Ampache Docker + Nginx reverse proxy 502 error

### ISSUE THREAD

**Issue by jrejaud** [ampache/ampache#3202]
I've gotten ampache-docker to work fine over a non-encrypted connection (mysite.com:8051), but when I try to setup TLS/SSL using NGINX as a reverse proxy, I get a 502 error and can't figure out what is wrong.

Attached are my:

docker-compose file
```
version: '3'

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    ports:
      - 8051:80
      - 8543:443
    volumes:
      - ./data/config:/var/www/config
      - ./data/log:/var/log/ampache
      - /home/jrejaud/Music:/media
      - ./data/mysql:/var/lib/mysql
```

nginx file
```
server {

        server_name mySite.com;

        location / {
                proxy_pass https://localhost:8543;
        }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/xxx/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/xxx/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = mySite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80 ;
        listen [::]:80 ;

        server_name mySite.com;
    return 404; # managed by Certbot


}
```

And I've set the following in ampache.cfg.php:
```
local_web_path = "https://localhost:443"
force_ssl = "true"
web_path = ""
```

Please advise :(
