### ISSUE TITLE
How to add ampache as Sonos Service?

### ISSUE THREAD

**Issue by sebmuc99** [ampache/ampache#3747]
How can i add my ampache server as a sonos service? 

searching the web for 2 hours but couldn't find anything, maybe someone can help.

**Comment by dubwoc** [comment]
This is not possible. There was a project, https://github.com/hyperactivated/ampache-sonos, that attempt to do this some time ago. Someone would need to revive and update it as things have definitely changed since then.

**Comment by SuperFola** [comment]
I have some (dated) knowledge of PHP, but no knowledge about how Sonos API nor Ampache works (though I've used Ampache subsonic API), but I'm willing to try something, having acquired a Sonos speaker recently

**Comment by lachlan-00** [comment]
> found my solution already, i'm running bonob in a docker container
> 
> https://github.com/simojenki/bonob

seems like a cool project, were there any issues setting up?

**Comment by sebmuc99** [comment]
No issues, very easy to setup, here is my docker compose file:

```
version: "3.9"
services:
    ampache:
        image: ampache/ampache:nosql
        container_name: Ampache
        network_mode: bridge
        ports:
            - 8059:80
        restart: always
        labels:
            com.centurylinklabs.watchtower.enable: true
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - /volume1/docker/media/ampache/config:/var/www/config
            - /volume1/docker/media/ampache/log:/var/log/ampache
            - /volume1/media/musicLibrary:/media
        environment:
            UID: 1027
            GID: 100
            UMASK: 022
            TZ: Europe/Berlin
            
    ampachebonob:
        image: simojenki/bonob:latest
        container_name: AmpacheBonob
        network_mode: bridge
        ports:
            - "4535:4535"
        restart: always
        labels:
            com.centurylinklabs.watchtower.enable: true
        depends_on:
            - ampache
        environment:
            BNB_PORT: 4535
            BNB_SECRET: XXXXXXXXX
            BNB_SONOS_AUTO_REGISTER: true
            BNB_SONOS_DEVICE_DISCOVERY: true
            BNB_SONOS_SEED_HOST: 192.168.100.150
            BNB_SONOS_SERVICE_ID: 249
            BNB_SONOS_SERVICE_NAME: Ampache
            BNB_SUBSONIC_URL: http://192.168.100.30:8059
            BNB_URL: http://192.168.100.30:4535
            BNB_DISABLE_PLAYLIST_ART: false
            BNB_SUBSONIC_ARTIST_IMAGE_CACHE: "/mnt/cache"
            BNB_REPORT_NOW_PLAYING: false
            BNB_SCROBBLE_TRACKS: false
            TZ: Europe/Berlin
            UID: 1027
            GID: 100
            UMASK: 022            
        volumes:
            - /volume1/docker/media/ampache/bonobcache:/mnt/cache:rw

```
